name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Pull LFS Objects
      run: |
        git lfs pull
        git lfs checkout

    - name: Clone vcpkg
      run: git clone https://github.com/microsoft/vcpkg.git

    - name: Bootstrap vcpkg
      run: .\vcpkg\bootstrap-vcpkg.bat
      shell: pwsh

    - name: Install dependencies
      run: |
        .\vcpkg\vcpkg.exe install `
          glfw3:x64-windows `
          glm:x64-windows `
          assimp:x64-windows `
          vulkan:x64-windows
      shell: pwsh

    - name: Configure CMake
      run: |
        cmake -B build -S . `
          -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake"
      shell: pwsh

    - name: Build
      run: cmake --build build --config Release
    
    - name: Copy dlls
      run: cp -a vendor/dlls/. build/Release/
      shell: bash

    - name: Create src folder	
      run: mkdir -p build/Release/src

    - name: Copy shaders
      run: cp -a src/shaders build/Release/src
      shell: bash

    - name: Copy resources
      run: cp -a resource build/Release/
      shell: bash

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: vulkan-build
        path: build/Release/

    - name: Test
      run: ctest --test-dir build -C Release --output-on-failure
